import { Database as DB} from '@/lib/database.types';

// Makes Supabase Autogenerated DB types available
declare global {
    type Database = DB;
    type TweetWithAuthor = Tweet & {
        author: Profile;
        likes: number;
        user_has_liked_tweet: boolean;
    }
}